### ISSUE TITLE
Could you help me with my project?

### ISSUE THREAD

**Issue by danielteberian** [berkus/berkus#1]
I see you are into Rust, and you're into OS-development, and you are far more knowledgable than I. Could you help me with my OS project? I have some questions that I think you could answer. Thanks for starring my repository, good luck, and God bless :)

P.S. If you are interested in helping, open an issue on my OS' main repository and we can figure things out. (LibertyOS-Development/kernel)

- Daniel

**Comment by berkus** [comment]
Sure.
